import { describe, it, expect, vi, beforeEach } from 'vitest';
import * as fc from 'fast-check';

vi.mock('../lib/prisma', () => ({
  prisma: {
    invitation: {
      create: vi.fn(),
    },
  },
}));

import { prisma } from '../lib/prisma';
import { generateInvitationCode } from '../lib/crypto';
import { createInvitation } from '../modules/invitations/invitation.service';

/**
 * Property 6: Unicidad de códigos de invitación
 * Validates: Requirements 2.1
 *
 * For any sequence of N invitations generated by one or more therapists,
 * all generated codes must be unique (no collisions).
 */
describe('Feature: coterapeuta-app, Property 6: Unicidad de códigos de invitación', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('generateInvitationCode produces unique UUIDs across N calls', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: 2, max: 200 }),
        (n) => {
          const codes = Array.from({ length: n }, () => generateInvitationCode());
          const uniqueCodes = new Set(codes);
          expect(uniqueCodes.size).toBe(n);
        }
      ),
      { numRuns: 100 }
    );
  });

  it('createInvitation generates unique codes for concurrent therapists', async () => {
    // Track all codes passed to prisma.invitation.create
    const createdCodes: string[] = [];

    vi.mocked(prisma.invitation.create).mockImplementation(({ data }: any) => {
      createdCodes.push(data.code);
      return Promise.resolve({
        id: 'inv-id-' + Math.random(),
        code: data.code,
        therapistId: data.therapistId,
        expiresAt: data.expiresAt,
        usedAt: null,
        createdAt: new Date(),
      }) as any;
    });

    await fc.assert(
      fc.asyncProperty(
        fc.array(fc.uuid(), { minLength: 2, maxLength: 50 }),
        async (therapistIds) => {
          const beforeCount = createdCodes.length;
          await Promise.all(therapistIds.map(id => createInvitation(id)));
          const newCodes = createdCodes.slice(beforeCount);
          const uniqueNewCodes = new Set(newCodes);
          expect(uniqueNewCodes.size).toBe(newCodes.length);
        }
      ),
      { numRuns: 20 }
    );
  });
});
